src/Entity/Paiement.php
<?php

namespace App\Entity;

use App\Repository\PaiementRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PaiementRepository::class)]
class Paiement
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $dateAchat = null;

    #[ORM\ManyToOne(inversedBy: 'paiements')]
    private ?Tarif $tarif = null;

    #[ORM\ManyToOne(inversedBy: 'paiements')]
    private ?User $user = null;

    #[ORM\Column(length: 70)]
    private ?string $nom = null;

    #[ORM\Column(length: 30)]
    private ?string $prenom = null;

    #[ORM\Column(length: 150, nullable: true)]
    private ?string $entreprise = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 13)]
    private ?string $tel = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse = null;

    #[ORM\ManyToOne(inversedBy: 'paiements')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Statut $Statut = null;

    #[ORM\ManyToOne(inversedBy: 'paiements')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Metier $metier = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->dateAchat;
    }

    public function setDate(\DateTimeInterface $dateAchat): static
    {
        $this->dateAchat = $dateAchat;

        return $this;
    }

    public function getTarif(): ?Tarif
    {
        return $this->tarif;
    }

    public function setTarif(?Tarif $tarif): static
    {
        $this->tarif = $tarif;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEntreprise(): ?string
    {
        return $this->entreprise;
    }

    public function setEntreprise(?string $entreprise): static
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(string $tel): static
    {
        $this->tel = $tel;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getStatut(): ?Statut
    {
        return $this->Statut;
    }

    public function setStatut(?Statut $Statut): static
    {
        $this->Statut = $Statut;

        return $this;
    }

    public function getMetier(): ?Metier
    {
        return $this->metier;
    }

    public function setMetier(?Metier $metier): static
    {
        $this->metier = $metier;

        return $this;
    }
}

templates/index/choix.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Choix d'inscription</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{{ asset("/design/assets/vendors/mdi/css/materialdesignicons.min.css") }}">
    <link rel="stylesheet" href="{{ asset("/design/assets/vendors/css/vendor.bundle.base.css")}}">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="{{ asset("/design/assets/css/style.css")}}">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="{{ asset("/design/assets/images/favicon.png")}}" />
</head>

<body>
<div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="row w-100 m-0">
            <div class="content-wrapper full-page-wrapper d-flex align-items-center auth login-bg text-center">
                <div class="card col-lg-4 mx-auto">
                    <div class="card-body px-5 py-5 ">
                        {% set error = false %}
                        {% for message in app.flashes('error') %}
                            {% set error = true %}
                            <p>{{ message }}</p>
                            <p class="lead"> Merci de choisir si vous êtes indépendant ou si vous êtes salarié d'une entreprise. </p>
                            <div>
                                <button type="button" class="btn btn-outline-primary btn-lg btn-block m-1" style="font-size: larger" onclick="window.location.href=' {{ path("independantAjouter") }}'">Indépendant</button>
                                <button type="button" class="btn btn-outline-danger btn-lg btn-block m-1" style="font-size: larger" onclick="window.location.href='{{ path("entrepriseAjouter") }}'">Entreprise</button>
                            </div>
                        {% endfor %}
                        {% if error == false %}
                        <p class="lead"> Merci de choisir si vous êtes indépendant ou si vous êtes salarié d'une entreprise. </p>
                        <div>
                            <button type="button" class="btn btn-outline-secondary btn-lg btn-block m-1" style="font-size: larger" onclick="window.location.href=' {{ path("independantAjouter") }}'">Indépendant</button>
                            <button type="button" class="btn btn-outline-secondary btn-lg btn-block m-1" style="font-size: larger" onclick="window.location.href='{{ path("entrepriseAjouter") }}'">Entreprise</button>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- container-scroller -->
<!-- plugins:js -->
<script src="{{ asset("/design/assets/vendors/js/vendor.bundle.base.js")}}"></script>
<!-- endinject -->
<!-- Plugin js for this page -->
<!-- End plugin js for this page -->
<!-- inject:js -->
<script src="{{ asset("/design/assets/js/off-canvas.js")}}"></script>
<script src="{{ asset("/assets/js/hoverable-collapse.js")}}"></script>
<script src="{{ asset("/assets/js/misc.js")}}"></script>
<script src="{{ asset("/assets/js/settings.js")}}"></script>
<script src="{{ asset("/assets/js/todolist.js")}}"></script>
</body>

</html>

templates/index/mentionlegale.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mention legale {% endblock %}

{% block body %}

    <section>

        <div>
            <h1>Mentions Légales de LaBananerie</h1>
            <br>
            <section>
                <h2>Identification de l'éditeur et de l’hébergeur du site</h2>

                <p><strong>Nom de l'entreprise :</strong> LaBananerie</p>
                <p><strong>Forme juridique :</strong> [SARL / SAS / autre forme juridique]</p>
                <p><strong>Siège social :</strong> [Adresse complète]</p>
                <p><strong>Numéro de téléphone :</strong> [Numéro]</p>
                <p><strong>Adresse e-mail :</strong> <a href="mailto:icilabananerie@gmail.com">icilabananerie@gmail.com</a></p>
                <p><strong>Numéro d'enregistrement au registre du commerce :</strong> [Numéro]</p>
                <p><strong>Directeur de la publication :</strong> [Nom du responsable]</p>
                <p><strong>Nom de l'hébergeur :</strong> [Nom de l'hébergeur]</p>
                <p><strong>Adresse de l'hébergeur :</strong> [Adresse de l'hébergeur]</p>
                <p ><strong>Numéro de téléphone de l'hébergeur :</strong> [Numéro]</p>
            </section>
            <section>
                <h2>Propriété intellectuelle</h2>
                <p>Le contenu du site (textes, images, design, marque, logo, etc.) appartient exclusivement à LaBananerie. Toute reproduction, représentation, modification ou adaptation de tout ou partie des éléments du site, quel que soit le moyen ou le procédé utilisé, est interdite, sauf autorisation écrite préalable de LaBananerie.</p>
            </section>
            <section>
                <h2>Collecte de données personnelles</h2>
                <p>Dans le cadre de son site vitrine, LaBananerie collecte uniquement l'adresse e-mail des utilisateurs, et ce uniquement lorsque ceux-ci fournissent volontairement cette information. Cette collecte sert exclusivement à la communication avec les utilisateurs. LaBananerie s'engage à ne pas divulguer ces informations à des tiers et à les utiliser uniquement dans le cadre de ses activités professionnelles.</p>
            </section>
            <section>
                <h2 class=>Politique de confidentialité</h2>
                <p>Toutes les données personnelles collectées sont traitées avec la plus stricte confidentialité. LaBananerie s'engage à respecter les dispositions législatives relatives à la protection des données personnelles.</p>
            </section>
            <section>
                <h2>Cookies</h2>
                <p>(Si on les collecte) Le site de LaBananerie utilise des cookies pour améliorer l'expérience utilisateur. Ces cookies ne collectent pas d'informations personnelles et sont utilisés uniquement à des fins statistiques et fonctionnelles.</p>
            </section>
            <section>
                <h2>Liens hypertextes</h2>
                <p>Le site de LaBananerie peut contenir des liens hypertextes vers d’autres sites. LaBananerie n'est pas responsable du contenu et du fonctionnement de ces sites externes.</p>
            </section>
            <section>
                <h2>Modification des mentions légales</h2>
                <p>LaBananerie se réserve le droit de modifier à tout moment les présentes mentions légales. Les utilisateurs sont encouragés à les consulter régulièrement.</p>
            </section>
            <section>
                <h2>Loi applicable et juridiction compétente</h2>
                <p>Les présentes mentions légales sont régies par la loi française. En cas de litige, les tribunaux français seront seuls compétents.</p>
            </section>
            <p><em>Date de dernière mise à jour : 9 janvier 2024</em></p>
        </div>


    </section>

{% endblock %}

templates/index/modalDetail.html.twig
{#{% extends 'base.html.twig' %}#}

{#{% block title %}Tableau de bord{% endblock %}#}
<link rel="stylesheet" href="{{ asset("design/assets/css/style.css")}}" >
<link rel="stylesheet" href="{{ asset("/design/assets/vendors/mdi/css/materialdesignicons.min.css")}}">
<link rel="stylesheet" href="{{ asset("design/assets/vendors/css/vendor.bundle.base.css")}}">

<link rel="stylesheet" href="{{ asset("design/assets/vendors/jvectormap/jquery-jvectormap.css")}}">
<link rel="stylesheet" href="{{ asset("design/assets/vendors/flag-icon-css/css/flag-icon.min.css")}}">
<link rel="stylesheet" href="{{ asset("design/assets/vendors/owl-carousel-2/owl.carousel.min.css")}}">
<link rel="stylesheet" href="{{ asset("design/assets/vendors/owl-carousel-2/owl.theme.default.min.css")}}">

{% for message in app.flashes('success') %}
    <div class="card-body" style="margin-bottom: 20px">
        <blockquote class="blockquote blockquote-primary">
            <h6 class="text-success">{{ message }}</h6>
        </blockquote>
    </div>
{% endfor %}
{% for message in app.flashes('error') %}
    <div class="card-body" style="margin-bottom: 20px">
        <blockquote class="blockquote blockquote-primary">
            <p class="text-danger">ERREUR :</p>
            <footer class="text-danger">{{ message }}</footer>
        </blockquote>
    </div>
{% endfor %}



{% if succes %}
    <div class="container">
        <div class="row" style="padding-top: 20px">
            <div class="col-cm-12">
                <h2>MA RÉSERVATION:</h2>
                <h3 class="text-secondary"> Espace : {{ reservation.espace.libelle }}</h3>

                <div class="row" style="padding-top: 20px">
                    <div class="col-md-12">
                        <label class="text-secondary">JOUR :</label>
                        {{ reservation.date|date('d/m/Y') }}
                    </div>
                </div>

                <div class="row" style="padding-top: 20px">
                    <div style="width: 50%;">
                        <label class="text-secondary">HEURE DE DÉBUT :</label>
                        {{ reservation.heureDebut }}h
                    </div>

                    <div style="width: 50%;">
                        <label class="text-secondary">HEURE DE FIN :</label>
                        {{ reservation.heureFin }}h
                    </div>
                </div>
                <div class="row" style="padding-top: 20px">
                    <div class="col-md-12">
                        <label class="text-secondary">DÉTAILS DE RÉSERVATION :</label>
                        {{ reservation.libelle }}
                    </div>
                </div>
                <div style="padding-top: 20px" id="btnform">
                    {% if annulable %}
                        <a href="{{ path('detailReservation', {'id': reservation.id,'annuler': true}) }}" id="btnConfirm" type="submit" class="btn btn-danger btn-fw">ANNULER MA RÉSERVATION</a>
                        <h4 id="temoins" style="display: none" class="">Annulation en cours...</h4>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endif %}
<script>

    document.addEventListener("DOMContentLoaded", function () {
        document.getElementById("btnConfirm").addEventListener("click", function () {
            document.getElementById("btnConfirm").style.display = "none";
            document.getElementById("temoins").style.display = "block";
        })
    });

</script>

templates/index/reservation.html.twig
{#{% extends 'base.html.twig' %}#}

{#{% block title %}Tableau de bord{% endblock %}#}
<link rel="stylesheet" href="{{ asset("design/assets/css/style.css")}}" >
<link rel="stylesheet" href="{{ asset("/design/assets/vendors/mdi/css/materialdesignicons.min.css")}}">
<link rel="stylesheet" href="{{ asset("design/assets/vendors/css/vendor.bundle.base.css")}}">

<link rel="stylesheet" href="{{ asset("design/assets/vendors/jvectormap/jquery-jvectormap.css")}}">
<link rel="stylesheet" href="{{ asset("design/assets/vendors/flag-icon-css/css/flag-icon.min.css")}}">
<link rel="stylesheet" href="{{ asset("design/assets/vendors/owl-carousel-2/owl.carousel.min.css")}}">
<link rel="stylesheet" href="{{ asset("design/assets/vendors/owl-carousel-2/owl.theme.default.min.css")}}">

{#{% block body %}#}
{% for message in app.flashes('success') %}
    <div class="card-body" style="margin-bottom: 20px">
        <blockquote class="blockquote blockquote-primary">
            <footer class="blockquote-footer text-success">{{ message }}</footer>
        </blockquote>
    </div>
{% endfor %}

{% for message in app.flashes('error') %}
    <div class="card-body" style="margin-bottom: 20px">
        <blockquote class="blockquote blockquote-primary">
            <p class="text-danger">ERREUR :</p>
            <footer class="blockquote-footer text-danger">{{ message }}</footer>
        </blockquote>
    </div>
{% endfor %}
{% if succes %}
    {{ form_start(form) }}
    {{ form_widget(form._token) }}
    <div class="container">
        <div class="row" style="padding-top: 20px">
            <div class="col-cm-12">
                <h2>Détails de la réservation:</h2>
                <h3 class="text-secondary"> Espace : {{ reservation.espace.libelle }}</h3>

                <div class="row" style="padding-top: 20px">
                    <div class="col-md-12">
                        <label class="text-secondary">JOUR :</label>
                        {{ form_widget(form.date) }}
                    </div>
                </div>

                <div class="row" style="padding-top: 20px">
                    <div style="width: 50%;">
                        {{ form_widget(form.heureDebut) }}
                    </div>

                    <div style="width: 50%;">
                        {{ form_widget(form.heureFin) }}
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        {{ form_errors(form.heureFin) }}
                    </div>
                </div>
                <div class="row" style="padding-top: 20px">
                    <div class="col-md-12">
                        <label class="text-secondary">DÉTAILS DE LA RÉSERVATION :</label>
                        {{ form_widget(form.libelle) }}
                    </div>
                </div>
                {{ form_widget(form.espace) }}
                {{ form_widget(form.user) }}
                <div class="row" style="padding-top: 20px">
                    <div class="col-md-12">
                        <label class="text-secondary">MODALITÉS DE RÉSERVATION :</label>
                    </div>
                </div>
                <div class="row flex-c-c" style="padding-top: 10px;">
                    <div class="col-lg-12">
                        <div class="table-responsive">
                            <table class="table table-bordered text-md-center" style="table-layout: fixed;">
                                {% set un = false %}
                                {% for coin in reservation.espace.tarifEspaceTarifs %}
                                    {% if coin.heure == 1 %}
                                        {% set un = true %}
                                    {% endif %}
                                {% endfor %}
                                <thead>
                                <tr>
                                    <th>Heures</th>
                                    <th>Tarif B.Coins</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>

                                <tr>
                                    <th>9h-13h</th>
                                    {% set havePrix = false %}
                                    {% for coin in reservation.espace.tarifEspaceTarifs %}
                                        {% if coin.heure == 4 %}
                                            {% set havePrix = true %}
                                            <th>
                                                <h6>{{ coin.prix }} B.Coins</h6>
                                            </th>
                                        {% endif %}

                                    {% endfor %}
                                    {% if havePrix == false %}
                                        <th colspan="2"><label> Sur devis </label></th>
                                    {% else %}
                                        <th>{{ form_widget(form.matin,{'attr': {'onClick': 'matin()'}}) }}</th>

                                    {% endif %}
                                </tr>
                                <tr>
                                    <th>14h-18h</th>
                                    {% for coin in reservation.espace.tarifEspaceTarifs %}
                                        {% if coin.heure == 4 %}
                                            {% set havePrix = true %}
                                            <th>
                                                <h6>{{ coin.prix }} B.Coins</h6>
                                            </th>
                                        {% endif %}
                                    {% endfor %}
                                    {% if havePrix == true %}
                                        <th>{{ form_widget(form.apresmidi,{'attr': {'onClick': 'apresMidi()'}}) }}</th>
                                    {% endif %}
                                </tr>
                                <tr>
                                    <th>9h-18h</th>
                                    {% set havePrix = false %}
                                    {% for coin in reservation.espace.tarifEspaceTarifs %}
                                        {% if coin.heure == 9 %}
                                            {% set havePrix = true %}
                                            <th>
                                                <h6>{{ coin.prix }} B.Coins</h6>
                                            </th>
                                        {% endif %}
                                    {% endfor %}
                                    {% if havePrix == false %}
                                        <th colspan="2"><label> Sur devis </label></th>
                                    {% else %}
                                        <th>{{ form_widget(form.journee,{'attr': {'onClick': 'journee()'}}) }}</th>
                                    {% endif %}
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="row" style="padding-top: 20px">
                    <h4 id="temoins" style="display: none" class="">Réservation en cours...</h4>
                </div>
            </div>
        </div>
    </div>
    {{ form_end(form,{"render_rest": false}) }}
{% endif %}

<script>

    function matin() {
        document.getElementById('reservation_heureDebut').value = 9;
        document.getElementById('reservation_heureFin').value = 13;
    }

    function apresMidi() {
        document.getElementById('reservation_heureDebut').value = 14;
        document.getElementById('reservation_heureFin').value = 18;
    }

    function journee() {
        document.getElementById('reservation_heureDebut').value = 9;
        document.getElementById('reservation_heureFin').value = 18;
    }


    document.addEventListener("DOMContentLoaded", function () {
        for (let i = 0; i < document.getElementsByClassName("btnConfirm").length; i++) {
            document.getElementsByClassName("btnConfirm")[i].addEventListener("click", function () {
                if (document.getElementById("reservation_libelle").value !== '') {
                    for (let j = 0; j < document.getElementsByClassName("btnConfirm").length; j++) {
                        document.getElementsByClassName("btnConfirm")[j].style.display = "none";
                    }
                    document.getElementById("temoins").style.display = "block";
                }
            });
        }

        // défini l'heure suivant le clic de l'utilisateur
        var heure = location.search.split('=')[3].split('/');
        document.getElementById('reservation_heureDebut').value = heure[0];
        document.getElementById('reservation_heureFin').value = heure[1];

    });

</script>

{#{% endblock %}#}

templates/index/reservationHeure.html.twig
{#{% extends 'base.html.twig' %}#}

{#{% block title %}Tableau de bord{% endblock %}#}
<link rel="stylesheet" href="{{ asset("design/assets/css/style.css")}}" >
<link rel="stylesheet" href="{{ asset("/design/assets/vendors/mdi/css/materialdesignicons.min.css")}}">
<link rel="stylesheet" href="{{ asset("design/assets/vendors/css/vendor.bundle.base.css")}}">

<link rel="stylesheet" href="{{ asset("design/assets/vendors/jvectormap/jquery-jvectormap.css")}}">
<link rel="stylesheet" href="{{ asset("design/assets/vendors/flag-icon-css/css/flag-icon.min.css")}}">
<link rel="stylesheet" href="{{ asset("design/assets/vendors/owl-carousel-2/owl.carousel.min.css")}}">
<link rel="stylesheet" href="{{ asset("design/assets/vendors/owl-carousel-2/owl.theme.default.min.css")}}">

{#{% block body %}#}
{% for message in app.flashes('success') %}
    <div class="card-body" style="margin-bottom: 20px">
        <blockquote class="blockquote blockquote-primary">
            <footer class="blockquote-footer text-success">{{ message }}</footer>
        </blockquote>
    </div>
{% endfor %}

{% for message in app.flashes('error') %}
    <div class="card-body" style="margin-bottom: 20px">
        <blockquote class="blockquote blockquote-primary">
            <p class="text-danger">ERREUR :</p>
            <footer class="blockquote-footer text-danger">{{ message }}</footer>
        </blockquote>
    </div>
{% endfor %}
{% if succes %}
    {{ form_start(form) }}
    {{ form_widget(form._token) }}
    <div class="container">
        <div class="row" style="padding-top: 20px">
            <div class="col-cm-12">
                <h2>Détails de la réservation:</h2>
                <h3 class="text-secondary"> Espace : {{ reservation.espace.libelle }}</h3>

                <div class="row" style="padding-top: 20px">
                    <div class="col-md-12">
                        <label class="text-secondary">JOUR :</label>
                        {{ form_widget(form.date) }}
                    </div>
                </div>
                
                <div class="row" style="padding-top: 20px">
                    <div style="width: 50%;">
                        <label class="text-secondary">HEURE DE DÉBUT :</label>
                        {{ form_widget(form.heureDebut) }}
                    </div>

                    <div style="width: 50%;">
                        <label class="text-secondary">HEURE DE FIN :</label>
                        {{ form_widget(form.heureFin) }}
                    </div>
                </div>

                <div class="row" style="padding-top: 20px">
                    <div class="col-md-12">
                        <h4>Réserver pour <span id="priceBuy"></span> B.Coins</h4>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        {{ form_errors(form.heureFin) }}
                    </div>
                </div>
                <div class="row" style="padding-top: 20px">
                    <div class="col-md-12">
                        <label class="text-secondary">DÉTAILS DE LA RÉSERVATION :</label>
                        {{ form_widget(form.libelle) }}
                    </div>
                </div>
                <div id="unite" style="display: none;">{{ unite }}</div>
                <div id="demi" style="display: none;">{{ demi }}</div>
                <div id="journee" style="display: none;">{{ journee }}</div>
                {{ form_widget(form.espace) }}
                {{ form_widget(form.user) }}

                <div style="padding-top: 15px" id="btnform">
                    <button id="btnConfirm" type="submit" class="btn btn-success btn-fw">CONFIRMER</button>
                    <h4 id="temoins" style="display: none" class="">Réservation en cours...</h4>
                </div>
            </div>
        </div>
    </div>
    {{ form_end(form,{"render_rest": false}) }}
{% endif %}

<script>

    function showPrice() {
        let hunite = parseInt(document.getElementById('unite').innerText);
        let hdemi = parseInt(document.getElementById('demi').innerText);
        let hjournee = parseInt(document.getElementById('journee').innerText);

        let hdebut = parseInt(document.getElementById('reservation_heure_heureDebut').value);
        let hfin = parseInt(document.getElementById('reservation_heure_heureFin').value);
        let time = hfin-hdebut;

        console.log(hunite, hdemi, hjournee, hdebut, hfin, time);

        if (time < 4){
            document.getElementById('priceBuy').innerText = hunite*time;
        }else if (time < 9){
            time = time-4;
            document.getElementById('priceBuy').innerText = hdemi+hunite*time;
        }else if (time === 9){
            document.getElementById('priceBuy').innerText = hjournee;
        }
    }

    function matin() {
        document.getElementById('reservation_heureDebut').value = 9;
        document.getElementById('reservation_heureFin').value = 13;
    }

    function apresMidi() {
        document.getElementById('reservation_heureDebut').value = 14;
        document.getElementById('reservation_heureFin').value = 18;
    }

    function journee() {
        document.getElementById('reservation_heureDebut').value = 9;
        document.getElementById('reservation_heureFin').value = 18;
    }


    document.addEventListener("DOMContentLoaded", function () {
        document.getElementById("btnConfirm").addEventListener("click", function () {
            if (document.getElementById("reservation_heure_libelle").value !== '') {
                document.getElementById("btnConfirm").style.display = "none";
                document.getElementById("temoins").style.display = "block";
            }
        });

        document.getElementById('reservation_heure_heureDebut').addEventListener('change', function() {
            ajusterHeureFin();
            showPrice();
        });

        document.getElementById('reservation_heure_heureFin').addEventListener('change', function() {
            ajusterHeureDebut();
            showPrice();
        });

        // Control si heure fin et plus grand que heure début

        function ajusterHeureFin() {
            var heureDebut = document.getElementById('reservation_heure_heureDebut');
            var heureFin = document.getElementById('reservation_heure_heureFin');
            if (parseInt(heureFin.value) <= parseInt(heureDebut.value)) {
                heureFin.value = parseInt(heureDebut.value) + 1;
            }
        }

        function ajusterHeureDebut() {
            var heureDebut = document.getElementById('reservation_heure_heureDebut');
            var heureFin = document.getElementById('reservation_heure_heureFin');
            if (parseInt(heureDebut.value) >= parseInt(heureFin.value)) {
                heureDebut.value = parseInt(heureFin.value) - 1;
            }
        }

        // défini l'heure suivant le clic de l'utilisateur
        var heure = location.search.split('=')[3].split('/');
        document.getElementById('reservation_heure_heureDebut').value = heure[0];
        document.getElementById('reservation_heure_heureFin').value = heure[1];

        showPrice();

    });

</script>

{#{% endblock %}#}